### PR TITLE
Added test example

### PR DESCRIPTION
**Pull request by parvit**
Added test example and made defines parameter optional.

### CODE REVIEW

**Comment by Vertexwahn** [comment]
@parvit All CI tests are failing :(

**Comment by Vertexwahn** [comment]
@parvit  `-D".join(defines)` seems not to work if `defines = []`

**Comment by parvit** [comment]
Yeah it was a stupid mistake (it is pretty late around here :D )

**Comment by Vertexwahn** [comment]
@parvit Thanks!

**Pull request merged**
